name: Creacion de proceso ETL

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENCIALES }}
        
    - name: Crear resource group
      run: |
          az group create \
            --name grupo_recursos_etl \
            --location "Mexico Central"
        
    - name: Crear infraestructura DB MYSQL
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: "grupo_recursos_etl"
        template: ./iac/azure_crear_infraestructura.bicep
        parameters: 'administratorLogin=${{ secrets.DB_USUARIO }} administratorLoginPassword=${{ secrets.DB_PASS }}'
        
    - name: Instalar cliente MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-client
        
    - name: Configurar base de datos y usuarios
      env:
        DB_USUARIO: ${{ secrets.DB_USUARIO }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_ETL_USUARIO: ${{ secrets.DB_ETL_USUARIO }}
        DB_ETL_PASS: ${{ secrets.DB_ETL_PASS }}
        DB_POWERBI_USUARIO: ${{ secrets.DB_POWERBI_USUARIO }}
        DB_POWERBI_PASS: ${{ secrets.DB_POWERBI_PASS }}
      run: |
        mysql -h "$MYSQL_HOST" \
              -u "$DB_USUARIO@$MYSQL_HOST" \
              -p"$DB_PASS" \
              -e "
                CREATE DATABASE IF NOT EXISTS $DB_NAME
                CHARACTER SET utf8mb4
                COLLATE utf8mb4_unicode_ci;

                CREATE USER IF NOT EXISTS '$DB_ETL_USUARIO'@'%' IDENTIFIED BY '$DB_ETL_PASS';
                GRANT CREATE, INSERT, DROP, REFERENCES ON $DB_NAME.* TO '$DB_ETL_USUARIO'@'%';

                CREATE USER IF NOT EXISTS '$DB_POWERBI_USUARIO'@'%' IDENTIFIED BY '$DB_POWERBI_PASS';
                GRANT REFERENCES ON $DB_NAME.* TO '$DB_POWERBI_USUARIO'@'%';

                FLUSH PRIVILEGES;
              "
