name: Docker build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USUARIO }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: pierosan/etl_fob_guard:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENCIALES }}

      - name: Actualizar imagen de contenedor
        run: |
            az containerapp job update \
            --name contenedoretl \
            --resource-group grupo_recursos_etl \
            --image docker.io/pierosan/etl_fob_guard:latest
